name: Run accessibility tests on JupyterLab

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  jlab-a11y:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository üõé
        uses: actions/checkout@v3

      - name: Cache conda üß†
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - name: Install miniconda üêç
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          python-version: 3.9
          use-only-tar-bz2: true

      - name: Sanity checks on environment üîç
        run: |
          conda info
          conda env list
          echo $CONDA_PREFIX

      - name: Install nox
        run: pip install nox

      - name: Setup and run tests
        run: |
          nox --forcecolor -s run_a11y_tests

      - name: Get run refs üè∑
        id: getrefs
        run: |
          export raw_branch=${GITHUB_REF#refs/heads/}
          echo "::set-output name=branch::${raw_branch//\//-}"
          echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Upload testing results üì§
        uses: actions/upload-artifact@v3
        # using default retention policy = 90 days
        with:
          name: jupyterlab-a11y-${{ steps.getrefs.outputs.branch }}-${{ steps.getrefs.outputs.sha8 }}
          path: |
            testing/jupyterlab/a11y-results/
