name: Run accessibility tests on JupyterLab

on: [workflow_dispatch, push, pull_request]

jobs:
  jlab-a11y:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./testing/jupyterlab
        shell: bash -l {0}
    steps:
      - name: Checkout repository ğŸ›
        uses: actions/checkout@v3

      - name: Cache conda ğŸ§ 
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - name: Install miniconda ğŸ
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          environment-file: ./testing/jupyterlab/environment.yml
          activate-environment: a11y-tests
          use-only-tar-bz2: true

      - name: Sanity checks on environment ğŸ”
        run: |
          conda info
          conda env list
          echo $CONDA_PREFIX

      - name: Install node dependencies ğŸ§¶
        run: |
          conda run --prefix $CONDA_PREFIX npm install
          conda run --prefix $CONDA_PREFIX npx playwright install chromium

      - name: Run tests  âœ…
        continue-on-error: true
        run: |
          conda run --prefix $CONDA_PREFIX npm test

      - name: Get run refs ğŸ·
        id: getrefs
        run: |
          export raw_branch=${GITHUB_REF#refs/heads/}
          echo "::set-output name=branch::${raw_branch//\//-}"
          echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Upload testing results ğŸ“¤
        uses: actions/upload-artifact@v3
        # using default retention policy = 90 days
        with:
          name: jupyterlab-a11y-${{ steps.getrefs.outputs.branch}}-${{ steps.getrefs.outputs.sha8 }}
          path: |
            testing/jupyterlab/test-results/
