name: Run accessibility tests on JupyterLab

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      repository:
        description: The JupyterLab repository or fork with owner, for example jupyterlab/jupyterlab.
        type: string
        required: true
      ref:
        description: The branch, tag, or SHA to checkout.
        type: string
        required: true
  workflow_dispatch:
    inputs:
      repository:
        description: The JupyterLab repository or fork with owner, for example jupyterlab/jupyterlab.
        required: false
      ref:
        description: The branch, tag, or SHA to checkout.
        required: false

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ðŸ—‚ Workspace is ${{ github.workspace }}"
      - run: echo "inputs.repository = ${{ inputs.repository }}"
      - run: echo "inputs.ref = ${{ inputs.ref }}"
      - run: echo "The workspace is $GITHUB_WORKSPACE"

  jlab-a11y:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jupyter-a11y-testing/testing/jupyterlab
        # Shell needs to use login mode in order to work with Conda.
        # https://github.com/marketplace/actions/setup-miniconda#important
        shell: bash -l {0}
    steps:
      - name: Checkout repository ðŸ›Ž
        uses: actions/checkout@v3
        with:
          repository: gabalafou/jupyter-a11y-testing
          path: jupyter-a11y-testing

      - name: Cache conda ðŸ§ 
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - name: Install miniconda ðŸ
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          environment-file: ./jupyter-a11y-testing/testing/jupyterlab/environment.yml
          activate-environment: a11y-tests
          use-only-tar-bz2: true

      - name: Sanity checks on environment ðŸ”
        run: |
          conda info
          conda env list
          echo $CONDA_PREFIX

      - name: Checkout JupyterLab
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository || 'jupyterlab/jupyterlab' }}
          ref: ${{ inputs.ref || 'master' }}
          path: jupyterlab

      - name: Build JupyterLab
        working-directory: jupyterlab
        run: |
          conda run --prefix $CONDA_PREFIX ./scripts/ci_install.sh
          conda run --prefix $CONDA_PREFIX jlpm run build

      - name: Check JupyterLab installation
        run: |
          which jupyter
          jupyter lab --version

      - name: Install node dependencies ðŸ§¶
        run: |
          conda run --prefix $CONDA_PREFIX npm install
          conda run --prefix $CONDA_PREFIX npx playwright install --with-deps chromium

      - name: Run tests  âœ…
        continue-on-error: true
        run: |
          conda run --prefix $CONDA_PREFIX npm test

      - name: Write GitHub Summary
        run: cat a11y-test-results.md >> $GITHUB_STEP_SUMMARY

      - name: Get run refs ðŸ·
        id: getrefs
        run: |
          export raw_branch=${GITHUB_REF#refs/heads/}
          echo "branch=${raw_branch//\//-}" >> $GITHUB_OUTPUT
          echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Upload Playwright report ðŸ“¤
        uses: actions/upload-artifact@v3
        # using default retention policy = 90 days
        with:
          name: playwright-report-${{ steps.getrefs.outputs.branch }}-${{ steps.getrefs.outputs.sha8 }}
          path: ./jupyter-a11y-testing/testing/jupyterlab/playwright-report/

      - name: Upload JSON test results ðŸ“‘
        uses: actions/upload-artifact@v3
        with:
          name: json-results-test-a11y-${{ steps.getrefs.outputs.branch }}-${{ steps.getrefs.outputs.sha8 }}
          path: ./jupyter-a11y-testing/testing/jupyterlab/a11y-test-results.json
