name: Run accessibility tests on JupyterLab

on:
  - workflow_dispatch

defaults:
  run:
    working-directory: ./testing/jupyterlab

jobs:
  jlab-a11y-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ğŸ›
        uses: actions/checkout@v3

      - name: Cache conda ğŸ§ 
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - name: Install miniconda ğŸ
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          environment-file: ./testing/jupyterlab/environment.yml
          activate-environment: a11y-tests
          use-only-tar-bz2: true

      - name: Cache npm ğŸ§ 
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install node dependencies ğŸ§¶
        run: |
          npm install
          npx playwright install

      - name: Run tests  âœ…
        continue-on-error: true
        run: npm test

      - name: Get run refs ğŸ·
        shell: bash
        id: getrefs
        run: |
          export raw_branch=${GITHUB_REF#refs/heads/}
          echo "::set-output name=branch::${raw_branch//\//-}"
          echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Upload testing results ğŸ“¤
        uses: actions/upload-artifact@v3
        # using default retention policy = 90 days
        with:
          name: jupyterlab-a11y-${{ steps.getrefs.outputs.branch}}-${{ steps.getrefs.outputs.sha8 }}
          path: |
            testing/jupyterlab/test-results/*.html
            testing/jupyterlab/test-results/**/*.html
            testing/jupyterlab/test-results/*.json
            testing/jupyterlab/test-results/**/*.json
